### ISSUE TITLE
Plugin should create "demo tiddlers" dynamically. 

### ISSUE THREAD

**Issue by pmario** [bimlas/tw5-kin-filter#2]
See my uni-link readme: https://wikilabs.github.io/editions/uni-link/#%24%3A%2Fplugins%2Fwikilabs%2Funi-link%2Freadme

At the end it contains 2 buttons, that create tiddlers, so users can use them for testing. 1 button to create the tiddlers and 1 button to remove them. 

If you do not need to open your test tiddlers in edit mode, you can use "action-setfield" instead of using tm-new-tiddler as I did.

**Comment by bimlas** [comment]
@pmario 

I've got your point: instead of adding some example tiddlers to the plugin (which may confuse the user when he/she is looking at shadow tiddlers) we could give the control to the user for creating these tiddlers.

I agree with you with one exception: I think it's better to create the tiddlers in the `$:/temp` namespace because if the user already has a `test-links` tiddler (this title seems to be general enough to be exist in any wiki), the button would overwrite it without a hassle. BTW the same is true for my example tiddlers (A, B, C).

**Comment by bimlas** [comment]
I've updated the plugin, what do you think?

**Comment by pmario** [comment]
looks good to me.
